version: '3'
volumes:
  girder: {}
  db: {}
  worker: {}
services:
  docker:
    image: 'docker:dind'
    privileged: true
    volumes:
      - 'worker:/tmp'

  mongo:
    image: mongo
    volumes:
      - 'db:/data/db'

  mq:
    image: rabbitmq
    ports:
      - '5672:5672'
    command: 'rabbitmq-server --hostname mq --name mq'

  girder:
    image: 'girder/girder'
    ports:
      - '8080:8080'
    volumes:
      - 'girder:/girder'
      - '..:/girder/plugins/video'
    depends_on:
      - mongo
    command: '-d mongodb://mongo:27017/girder'

  'pre-build':
    build: ./build
    volumes:
      - 'girder:/girder'
      - '..:/girder/plugins/video'
    depends_on:
      - mongo
      - girder
    links:
      - mongo
      - girder
    environment:
      - 'GIRDER_HOST=http://girder:8080'
      - 'GIRDER_ADMIN=admin:adminadmin'
      - 'GIRDER_GRIDFS_DB_NAME=local'
      - 'GIRDER_USER=girder:girder'
      - 'GIRDER_BROKER=amqp://guest@mq'
    command: ['--post-install']

  'core-build':
    build: ./build
    volumes:
      - 'girder:/girder'
      - '..:/girder/plugins/video'
    depends_on:
      - mongo
      - girder
      - 'pre-build'
    links:
      - mongo

  # 'video-build':
  #   build: ./build
  #   volumes:
  #     - 'girder:/girder'
  #     - '..:/girer/plugins/video'
  #   depends_on:
  #     - mongo
  #     - girder
  #     - 'pre-build'
  #   command: '--watch-plugin video'

  worker:
    build: ./worker
    volumes:
      - 'worker:/tmp'
      - './ffmpeg_local:/local_images/ffmpeg'
    depends_on:
      - docker
      - mq
    links:
      - docker
      - mq
    environment:
      - 'DOCKER_HOST=tcp://docker:2375'
      - 'CELERY_BROKER=amqp://guest@mq'
    command: ['--loglevel', 'INFO']
